version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/mallus-api
    depends_on:
      - database
    container_name: mallus-docker-api
    env_file:
      - .env

  database:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - mallus-docker-data:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: mallus-docker-db

# persisted storage
volumes:
  mallus-docker-data: